---
title: "Report"
subtitle: An interesting report
author: "Nick Hood"
date: "19/06/2020"
output: pdf_document
keywords: report, markdown
# abstract: An optional abstract
# pagestyle: plain # headings, plain or empty
papersize: a4
# fontsize: 12pt
# secunmdepth: 2
bibliography: /Users/nickhood/Dropbox/Bibliographies/PhD.bib
link-citations: true
---

# Introduction
In Ted Chiang's *Story of Your Life* [@Chiang2013], the linguist heroine Louise Banks asserts that interaction or specific instructional material is required in order to learn an alien language. When she does interact with aliens, she discovers that they have two distinct language systems: spoken and written, which are complete, independent and used for different purposes.

# How to make this
In R Studio, Knit: `CMD-shift-K`.

# Some quotes from the literature

>...there is a knife moving here. A very deadly one; an intellectual scalpel so swift and so sharp you sometimes don't see it moving. You get the illusion that all those parts are just there and are being named as they exist. But they can be named quite differently and organized quite differently depending on how the knife moves.

>For example, the feedback mechanism which includes the camshaft and cam chain and tappets and distributor exists only because of an unusual cut of this analytical knife. If you were to go to a motorcycle parts department and ask them for a feedback assembly they wouldn't know what the hell you were talking about. -- @Pirsig1984 [pp.68-69]

In this passage, the narrator shows that language conveys no meaning unless participants in the expression both understand the language in the same way. Science tries to use language in its various forms to explain models that infer the underlying truths they explain but even this has had its limitations.

>All science is either physics or stamp collecting -- Rutherford, quoted in @Birks1963 [p.108].

# References
